name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Give execute permissions to Gradle wrapper
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
